import test from 'node:test'
import assert from 'node:assert/strict'
import Database from 'better-sqlite3'
import { mkdtempSync, existsSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { runMigrations } from '../db/migration-runner.js'
import { teamFileMigrations } from '../db/team-file-migrations.js'
import { moveToTrash, purgeTrash, restoreTrash } from './trash-service.js'

function setup() { const root = mkdtempSync(join(tmpdir(), 'profer-trash-')); const db = new Database(':memory:'); db.exec(`CREATE TABLE file_manifests (workspace_id TEXT NOT NULL,file_path TEXT NOT NULL,file_name TEXT NOT NULL,is_directory INTEGER NOT NULL DEFAULT 0,size INTEGER NOT NULL DEFAULT 0,modified_at INTEGER NOT NULL,sha256 TEXT NOT NULL DEFAULT '',uploaded_by TEXT NOT NULL DEFAULT '',uploaded_by_name TEXT NOT NULL DEFAULT '',PRIMARY KEY(workspace_id,file_path));`); db.prepare(`INSERT INTO file_manifests (workspace_id,file_path,file_name,modified_at,uploaded_by) VALUES ('ws','资料/a.md','a.md',1,'creator'),('ws','资料','资料',1,'creator')`).run(); runMigrations(db, teamFileMigrations); const fileId = db.prepare("SELECT file_id FROM file_manifests WHERE file_path = '资料/a.md'").get().file_id; mkdirSync(join(root, 'ws', '资料'), { recursive: true }); writeFileSync(join(root, 'ws', '资料', 'a.md'), 'content'); return { db, root, fileId, close() { db.close(); rmSync(root, { recursive: true, force: true }) } } }
test('Given 活跃目录 When 移入回收站 Then 字节和子项状态迁移且资料保留', () => { const x = setup(); try { const result = moveToTrash(x.db, { filesDir: x.root, workspaceId: 'ws', filePath: '资料', actorId: 'creator', now: 100 }); assert.ok(existsSync(join(x.root, '.trash', 'ws', result.entryId, '资料', 'a.md'))); assert.equal(x.db.prepare("SELECT COUNT(*) c FROM file_manifests WHERE lifecycle_state='trashed'").get().c, 2); assert.equal(x.db.prepare('SELECT COUNT(*) c FROM file_metadata').get().c, 2) } finally { x.close() } })
test('Given 原路径被新资料复用 When 恢复 Then 创建已恢复副本并保持 fileId', () => { const x = setup(); try { const result = moveToTrash(x.db, { filesDir: x.root, workspaceId: 'ws', filePath: '资料/a.md', actorId: 'creator', now: 100 }); x.db.prepare("INSERT INTO file_manifests (workspace_id,file_path,file_name,modified_at,uploaded_by,lifecycle_state) VALUES ('ws','资料/a.md','a.md',200,'new','active')").run(); mkdirSync(join(x.root, 'ws', '资料'), { recursive: true }); writeFileSync(join(x.root, 'ws', '资料', 'a.md'), 'new'); const restored = restoreTrash(x.db, { filesDir: x.root, workspaceId: 'ws', entryId: result.entryId, actorId: 'admin', now: 200 }); assert.equal(restored.restoredPath, '资料/a（已恢复）.md'); assert.equal(x.db.prepare("SELECT file_id FROM file_manifests WHERE file_path = '资料/a（已恢复）.md'").get().file_id, x.fileId); assert.equal(x.db.prepare("SELECT lifecycle_state FROM file_manifests WHERE file_path = '资料/a.md'").get().lifecycle_state, 'active'); assert.equal(x.db.prepare("SELECT lifecycle_state FROM file_manifests WHERE file_path = '资料/a（已恢复）.md'").get().lifecycle_state, 'active') } finally { x.close() } })
test('Given 回收站条目 When 永久删除重复执行 Then 幂等且删除共享资料', () => { const x = setup(); try { const result = moveToTrash(x.db, { filesDir: x.root, workspaceId: 'ws', filePath: '资料/a.md', actorId: 'creator' }); assert.equal(purgeTrash(x.db, { filesDir: x.root, workspaceId: 'ws', entryId: result.entryId }).state, 'purged'); assert.equal(purgeTrash(x.db, { filesDir: x.root, workspaceId: 'ws', entryId: result.entryId }).state, 'already_purged'); assert.equal(x.db.prepare('SELECT COUNT(*) c FROM file_metadata WHERE file_id = ?').get(x.fileId).c, 0) } finally { x.close() } })
test('Given 回收站私有投影 When 尝试将其恢复为活动路径 Then 活跃 manifest 查询不命中', () => { const x = setup(); try { const result = moveToTrash(x.db, { filesDir: x.root, workspaceId: 'ws', filePath: '资料/a.md', actorId: 'creator' }); const row = x.db.prepare("SELECT file_path, lifecycle_state FROM file_manifests WHERE file_id = ?").get(x.fileId); assert.match(row.file_path, new RegExp(`^__trash__/${result.entryId}/`)); assert.equal(row.lifecycle_state, 'trashed'); assert.equal(x.db.prepare("SELECT COUNT(*) c FROM file_manifests WHERE lifecycle_state = 'active' AND file_path LIKE '__trash__/%'").get().c, 0) } finally { x.close() } })
