import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { executePresentVisualization, executeInspectVisualization, injectVisualizationMcpServer } from './agent-visualization-tools'
import { listVisualizations } from './visualization-records'
const roots: string[]=[]
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})})
function fixture(){const root=mkdtempSync(join(tmpdir(),'profer-visualize-tool-'));roots.push(root);const filePath=join(root,'view.html');writeFileSync(filePath,'<button>View</button>');return {input:{filePath,title:'View',summary:'Summary'},context:{sessionId:'s1',agentCwd:root,storageDir:join(root,'viz-store'),allowedRoots:[]}}}
describe('Visualize runtime contract',()=>{
 test('共用服务发布结构化结果和更新事件，inspect不伪称视觉验收',async()=>{const {input,context}=fixture();let updated:unknown;const result=await executePresentVisualization(input,{...context,onUpdate:(r)=>{updated=r}},'pi-call');expect(result.details.visualization.toolCallId).toBe('pi-call');expect(updated).toEqual(result.details.visualization);expect(JSON.parse(result.content[0]!.text).visualization.id).toBe(result.details.visualization.id);const inspected=await executeInspectVisualization({visualizationId:result.details.visualization.id},context);expect(JSON.parse(inspected.content[0]!.text).html).toContain('<button>View</button>')})
 test('取消信号和计划守卫拒绝新结果且不广播成功',async()=>{const {input,context}=fixture();let updates=0;const controller=new AbortController();controller.abort();await expect(executePresentVisualization(input,{...context,onUpdate:()=>{updates++}},'pi-call',controller.signal)).rejects.toThrow();await expect(executePresentVisualization(input,{...context,assertCanPresent:()=>{throw new Error('plan')},onUpdate:()=>{updates++}},'claude-call')).rejects.toThrow('plan');expect(await listVisualizations(context)).toEqual([]);expect(updates).toBe(0)})
 test('Claude工具可直接提交chart，不需要先写HTML文件',async()=>{let captured:any;const sdk={tool:(name:string,description:string,schema:any,execute:any)=>({name,description,schema,execute}),createSdkMcpServer:(value:any)=>{captured=value;return value}};const {context}=fixture();await injectVisualizationMcpServer(sdk as any,{},context);const tool=captured.tools.find((t:any)=>t.name==='present_visualization');const chart={chartType:'bar',xKey:'name',series:[{dataKey:'value'}],data:[{name:'A',value:12}]};const args={title:'原生图',summary:'示例',chart};expect(tool.schema.chart.parse(chart)).toEqual(chart);expect(tool.schema.filePath.parse(undefined)).toBeUndefined();const result=await tool.execute(args);expect(result.details.visualization.format).toBe('chart');expect(result.details.visualization.chart).toEqual(chart)})
 test('Claude MCP和Pi服务共用参数与事件名，单工具禁用不恢复',async()=>{let captured:any;const sdk={tool:(name:string,description:string,schema:any,execute:any)=>({name,description,schema,execute}),createSdkMcpServer:(value:any)=>{captured=value;return value}};const {context}=fixture();const servers={};await injectVisualizationMcpServer(sdk as any,servers,context,['present_visualization']);expect(captured.tools.map((t:any)=>t.name)).toEqual(['inspect_visualization']);await injectVisualizationMcpServer(sdk as any,servers,context);expect(captured.tools.map((t:any)=>t.name)).toEqual(['present_visualization','inspect_visualization']);expect(captured.tools[0].description).toContain('stateUpdated');expect(captured.tools[0].schema.baseRevision).toBeDefined()})
})
