import { Hono } from 'hono'
import crypto from 'node:crypto'
import { db } from '../db.js'
import { authMiddleware } from '../middleware.js'
import { logAudit } from '../audit.js'
import { broadcastEvent } from '../event-bus.js'
import { listActiveDeliveries } from '../team-planning/reminder-service.js'

export const planningRoutes = new Hono()
const allowedPriority = new Set(['low', 'medium', 'high'])

function access(c) {
  const workspaceId = c.req.param('id')
  const row = db.prepare(`SELECT wm.role FROM workspace_members wm JOIN workspaces w ON w.id=wm.workspace_id WHERE wm.workspace_id=? AND wm.user_id=? AND w.is_deleted=0`).get(workspaceId, c.get('userId'))
  return row ? workspaceId : null
}
async function body(c) { try { const value = await c.req.json(); return value && typeof value === 'object' && !Array.isArray(value) ? value : null } catch { return null } }
function tagsFor(workspaceId, targetType, targetId) { return db.prepare(`SELECT t.id,t.name,t.color,t.created_at,t.updated_at FROM planning_tag_links l JOIN planning_tags t ON t.workspace_id=l.workspace_id AND t.id=l.tag_id WHERE l.workspace_id=? AND l.target_type=? AND l.target_id=? ORDER BY t.name`).all(workspaceId,targetType,targetId).map(r=>({id:r.id,name:r.name,color:r.color||undefined,createdAt:r.created_at,updatedAt:r.updated_at})) }
function todoDto(row) { return { id: row.id, title: row.title, notes: row.notes || undefined, status: row.status, priority: row.priority, dueAt: row.due_at ?? undefined, groupId: row.group_id ?? undefined, tags:tagsFor(row.workspace_id,'todo',row.id), reminders:[], sessionLinks:[], assigneeId: row.assignee_id ?? undefined, createdBy: row.created_by, updatedBy: row.updated_by, version: row.version, createdAt: row.created_at, updatedAt: row.updated_at, completedAt: row.completed_at ?? undefined } }
function eventDto(row) { return { id: row.id, title: row.title, notes: row.notes || undefined, startAt: row.start_at, endAt: row.end_at ?? undefined, allDay: Boolean(row.all_day), groupId: row.group_id ?? undefined, tags:tagsFor(row.workspace_id,'calendar_event',row.id), reminders:[], todoId: row.todo_id ?? undefined, assigneeId: row.assignee_id ?? undefined, createdBy: row.created_by, updatedBy: row.updated_by, version: row.version, createdAt: row.created_at, updatedAt: row.updated_at } }
function validAssignee(workspaceId, id) { return !id || !!db.prepare('SELECT 1 FROM workspace_members WHERE workspace_id=? AND user_id=?').get(workspaceId, id) }
function replaceTags(workspaceId,targetType,targetId,tagIds,actorId,now) { if(!Array.isArray(tagIds))return; if(new Set(tagIds).size!==tagIds.length||tagIds.some(id=>typeof id!=='string'))throw new Error('标签参数非法'); const count=db.prepare(`SELECT COUNT(*) AS n FROM planning_tags WHERE workspace_id=? AND id IN (${tagIds.map(()=>'?').join(',')||"''"})`).get(workspaceId,...tagIds).n; if(count!==tagIds.length)throw new Error('包含不存在的团队标签'); db.prepare('DELETE FROM planning_tag_links WHERE workspace_id=? AND target_type=? AND target_id=?').run(workspaceId,targetType,targetId); const insert=db.prepare('INSERT INTO planning_tag_links(workspace_id,target_type,target_id,tag_id,created_at,created_by) VALUES(?,?,?,?,?,?)'); for(const tagId of tagIds)insert.run(workspaceId,targetType,targetId,tagId,now,actorId) }
function insertReminders(workspaceId, targetType, targetId, reminders, actorId, now) {
  if (!Array.isArray(reminders)) return
  const insert = db.prepare(`INSERT INTO planning_reminders(workspace_id,id,target_type,target_id,trigger_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`)
  for (const reminder of reminders) {
    if (!reminder || !Number.isFinite(reminder.triggerAt) || reminder.triggerAt <= 0) throw new Error('提醒时间非法')
    insert.run(workspaceId, crypto.randomUUID(), targetType, targetId, reminder.triggerAt, actorId, now, now)
  }
}
function changed(workspaceId, actorId, resource, id, action, email) { logAudit({ action: `planning.${resource}.${action}`, workspaceId, userId: actorId, userEmail: email, entityType: resource, entityId: id, detail: '' }); db.prepare('INSERT INTO planning_activities(id,workspace_id,resource_type,resource_id,action,actor_id,created_at) VALUES(?,?,?,?,?,?,?)').run(crypto.randomUUID(), workspaceId, resource, id, action, actorId, Date.now()); broadcastEvent(workspaceId, 'planning_changed', { resources: [resource === 'todo' ? 'todos' : 'calendar_events'], actorId, resourceId: id, action }) }

planningRoutes.get('/:id/planning/members', (c) => { const mw=authMiddleware(c); if(mw)return mw; const ws=access(c); if(!ws)return c.json({error:'无权访问工作区'},403); return c.json(db.prepare(`SELECT u.id,u.email,u.display_name,u.avatar,wm.role FROM workspace_members wm JOIN users u ON u.id=wm.user_id WHERE wm.workspace_id=? ORDER BY wm.joined_at`).all(ws).map(r=>({id:r.id,email:r.email,displayName:r.display_name,avatar:r.avatar,role:r.role}))) })
planningRoutes.get('/:id/planning/groups', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const scope=c.req.query('scope');if(scope!=='todo'&&scope!=='calendar')return c.json({error:'scope 必须为 todo 或 calendar'},400);return c.json(db.prepare('SELECT * FROM planning_groups WHERE workspace_id=? AND scope=? ORDER BY sort_order,name').all(ws,scope).map(r=>({id:r.id,scope:r.scope,name:r.name,color:r.color||undefined,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at}))) })
planningRoutes.post('/:id/planning/groups', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||!['todo','calendar'].includes(b.scope)||typeof b.name!=='string'||!b.name.trim()||b.name.length>100)return c.json({error:'分组参数非法'},400);const now=Date.now(),id=crypto.randomUUID(),user=c.get('userId');try{db.prepare('INSERT INTO planning_groups(workspace_id,id,scope,name,color,sort_order,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(ws,id,b.scope,b.name.trim(),typeof b.color==='string'?b.color:'',Number.isInteger(b.sortOrder)?b.sortOrder:0,user,user,now,now)}catch{return c.json({error:'同一范围下分组名称不能重复'},409)};broadcastEvent(ws,'planning_changed',{resources:[b.scope==='todo'?'todo_groups':'calendar_groups'],actorId:user});return c.json({id,scope:b.scope,name:b.name.trim(),color:b.color||undefined,sortOrder:Number.isInteger(b.sortOrder)?b.sortOrder:0,createdAt:now,updatedAt:now},201) })
planningRoutes.patch('/:id/planning/groups/:groupId', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||!['todo','calendar'].includes(b.scope)||(!('name'in b)&&!('color'in b)&&!('sortOrder'in b)))return c.json({error:'分组参数非法'},400);const old=db.prepare('SELECT * FROM planning_groups WHERE workspace_id=? AND id=? AND scope=?').get(ws,c.req.param('groupId'),b.scope);if(!old)return c.json({error:'分组不存在'},404);try{db.prepare('UPDATE planning_groups SET name=?,color=?,sort_order=?,updated_by=?,updated_at=? WHERE workspace_id=? AND id=? AND scope=?').run(typeof b.name==='string'&&b.name.trim()?b.name.trim():old.name,'color'in b?(b.color||''):old.color,Number.isInteger(b.sortOrder)?b.sortOrder:old.sort_order,c.get('userId'),Date.now(),ws,old.id,b.scope)}catch{return c.json({error:'同一范围下分组名称不能重复'},409)};broadcastEvent(ws,'planning_changed',{resources:[b.scope==='todo'?'todo_groups':'calendar_groups','todos','calendar_events'],actorId:c.get('userId')});const row=db.prepare('SELECT * FROM planning_groups WHERE workspace_id=? AND id=?').get(ws,old.id);return c.json({id:row.id,scope:row.scope,name:row.name,color:row.color||undefined,sortOrder:row.sort_order,createdAt:row.created_at,updatedAt:row.updated_at}) })
planningRoutes.delete('/:id/planning/groups/:groupId', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||!['todo','calendar'].includes(b.scope))return c.json({error:'scope 必填'},400);const changedRows=b.scope==='todo'?db.prepare('UPDATE planning_todos SET group_id=NULL WHERE workspace_id=? AND group_id=?').run(ws,c.req.param('groupId')).changes:db.prepare('UPDATE planning_calendar_events SET group_id=NULL WHERE workspace_id=? AND group_id=?').run(ws,c.req.param('groupId')).changes;const x=db.prepare('DELETE FROM planning_groups WHERE workspace_id=? AND id=? AND scope=?').run(ws,c.req.param('groupId'),b.scope);if(!x.changes)return c.json({error:'分组不存在'},404);broadcastEvent(ws,'planning_changed',{resources:[b.scope==='todo'?'todo_groups':'calendar_groups',b.scope==='todo'?'todos':'calendar_events'],actorId:c.get('userId')});return c.json({success:true,updatedItems:changedRows}) })
planningRoutes.get('/:id/planning/tags', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);return c.json(db.prepare('SELECT * FROM planning_tags WHERE workspace_id=? ORDER BY name').all(ws).map(r=>({id:r.id,name:r.name,color:r.color||undefined,createdAt:r.created_at,updatedAt:r.updated_at}))) })
planningRoutes.post('/:id/planning/tags', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||typeof b.name!=='string'||!b.name.trim()||b.name.length>100)return c.json({error:'标签名称非法'},400);const now=Date.now(),id=crypto.randomUUID(),user=c.get('userId');try{db.prepare('INSERT INTO planning_tags(workspace_id,id,name,color,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(ws,id,b.name.trim(),typeof b.color==='string'?b.color:'',user,user,now,now)}catch{return c.json({error:'标签名称不能重复'},409)};broadcastEvent(ws,'planning_changed',{resources:['tags'],actorId:user});return c.json({id,name:b.name.trim(),color:b.color||undefined,createdAt:now,updatedAt:now},201) })
planningRoutes.patch('/:id/planning/tags/:tagId', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||(!('name'in b)&&!('color'in b)))return c.json({error:'标签参数非法'},400);const old=db.prepare('SELECT * FROM planning_tags WHERE workspace_id=? AND id=?').get(ws,c.req.param('tagId'));if(!old)return c.json({error:'标签不存在'},404);try{db.prepare('UPDATE planning_tags SET name=?,color=?,updated_by=?,updated_at=? WHERE workspace_id=? AND id=?').run(typeof b.name==='string'&&b.name.trim()?b.name.trim():old.name,'color'in b?(b.color||''):old.color,c.get('userId'),Date.now(),ws,old.id)}catch{return c.json({error:'标签名称不能重复'},409)};broadcastEvent(ws,'planning_changed',{resources:['tags','todos','calendar_events'],actorId:c.get('userId')});const row=db.prepare('SELECT * FROM planning_tags WHERE workspace_id=? AND id=?').get(ws,old.id);return c.json({id:row.id,name:row.name,color:row.color||undefined,createdAt:row.created_at,updatedAt:row.updated_at}) })
planningRoutes.delete('/:id/planning/tags/:tagId', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);db.prepare('DELETE FROM planning_tag_links WHERE workspace_id=? AND tag_id=?').run(ws,c.req.param('tagId'));const x=db.prepare('DELETE FROM planning_tags WHERE workspace_id=? AND id=?').run(ws,c.req.param('tagId'));if(!x.changes)return c.json({error:'标签不存在'},404);broadcastEvent(ws,'planning_changed',{resources:['tags','todos','calendar_events'],actorId:c.get('userId')});return c.json({success:true}) })
planningRoutes.get('/:id/planning/todos', (c) => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);return c.json(db.prepare('SELECT * FROM planning_todos WHERE workspace_id=? AND deleted_at IS NULL ORDER BY updated_at DESC').all(ws).map(todoDto)) })
planningRoutes.post('/:id/planning/todos', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||typeof b.title!=='string'||!b.title.trim()||b.title.length>500)return c.json({error:'标题不能为空且最长 500 字'},400);if(!validAssignee(ws,b.assigneeId))return c.json({error:'负责人不是工作区成员'},400);const now=Date.now(),id=crypto.randomUUID(),user=c.get('userId');const priority=allowedPriority.has(b.priority)?b.priority:'medium';db.prepare('INSERT INTO planning_todos(workspace_id,id,title,notes,priority,due_at,group_id,assignee_id,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(ws,id,b.title.trim(),typeof b.notes==='string'?b.notes:'',priority,Number.isFinite(b.dueAt)?b.dueAt:null,typeof b.groupId==='string'?b.groupId:null,b.assigneeId||null,user,user,now,now);replaceTags(ws,'todo',id,b.tagIds,user,now);insertReminders(ws,'todo',id,b.reminders,user,now);const row=db.prepare('SELECT * FROM planning_todos WHERE workspace_id=? AND id=?').get(ws,id);changed(ws,user,'todo',id,'create',c.get('userEmail'));return c.json(todoDto(row),201) })
planningRoutes.patch('/:id/planning/todos/:todoId', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||(!Number.isInteger(b.expectedVersion)&&!Number.isFinite(b.expectedUpdatedAt)))return c.json({error:'需提供 expectedVersion'},400);if('assigneeId'in b&&!validAssignee(ws,b.assigneeId))return c.json({error:'负责人不是工作区成员'},400);const old=db.prepare('SELECT * FROM planning_todos WHERE workspace_id=? AND id=? AND deleted_at IS NULL').get(ws,c.req.param('todoId'));if(!old)return c.json({error:'Todo 不存在'},404);if((Number.isInteger(b.expectedVersion)&&old.version!==b.expectedVersion)||(Number.isFinite(b.expectedUpdatedAt)&&old.updated_at!==b.expectedUpdatedAt))return c.json({error:'事项已被其他成员修改，请重新加载后再试',code:'PLANNING_VERSION_CONFLICT',current:todoDto(old)},409);if(typeof b.title==='string'&&(!b.title.trim()||b.title.length>500))return c.json({error:'标题不能为空且最长 500 字'},400);const now=Date.now(),status=['open','completed'].includes(b.status)?b.status:old.status,completedAt=status==='completed'?(old.completed_at||now):null;replaceTags(ws,'todo',old.id,b.tagIds,c.get('userId'),now);db.prepare(`UPDATE planning_todos SET title=?,notes=?,priority=?,due_at=?,group_id=?,assignee_id=?,status=?,completed_at=?,updated_by=?,updated_at=?,version=version+1 WHERE workspace_id=? AND id=?`).run(typeof b.title==='string'?b.title.trim():old.title,typeof b.notes==='string'?b.notes:old.notes,allowedPriority.has(b.priority)?b.priority:old.priority,'dueAt'in b?(Number.isFinite(b.dueAt)?b.dueAt:null):old.due_at,'groupId'in b?(b.groupId||null):old.group_id,'assigneeId'in b?(b.assigneeId||null):old.assignee_id,status,completedAt,c.get('userId'),now,ws,old.id);const row=db.prepare('SELECT * FROM planning_todos WHERE workspace_id=? AND id=?').get(ws,old.id);changed(ws,c.get('userId'),'todo',old.id,'update',c.get('userEmail'));return c.json(todoDto(row)) })
planningRoutes.delete('/:id/planning/todos/:todoId', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const x=db.prepare('UPDATE planning_todos SET deleted_at=?,updated_at=?,updated_by=?,version=version+1 WHERE workspace_id=? AND id=? AND deleted_at IS NULL').run(Date.now(),Date.now(),c.get('userId'),ws,c.req.param('todoId'));if(!x.changes)return c.json({error:'Todo 不存在'},404);changed(ws,c.get('userId'),'todo',c.req.param('todoId'),'delete',c.get('userEmail'));return c.json({success:true}) })
planningRoutes.get('/:id/planning/calendar-events', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);return c.json(db.prepare('SELECT * FROM planning_calendar_events WHERE workspace_id=? AND deleted_at IS NULL ORDER BY start_at').all(ws).map(eventDto)) })
planningRoutes.post('/:id/planning/calendar-events', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||typeof b.title!=='string'||!b.title.trim()||!Number.isFinite(b.startAt))return c.json({error:'标题和开始时间必填'},400);if(!validAssignee(ws,b.assigneeId))return c.json({error:'负责人不是工作区成员'},400);const now=Date.now(),id=crypto.randomUUID(),user=c.get('userId');db.prepare('INSERT INTO planning_calendar_events(workspace_id,id,title,notes,start_at,end_at,all_day,group_id,todo_id,assignee_id,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(ws,id,b.title.trim(),typeof b.notes==='string'?b.notes:'',b.startAt,Number.isFinite(b.endAt)?b.endAt:null,b.allDay?1:0,b.groupId||null,b.todoId||null,b.assigneeId||null,user,user,now,now);replaceTags(ws,'calendar_event',id,b.tagIds,user,now);insertReminders(ws,'calendar_event',id,b.reminders,user,now);const row=db.prepare('SELECT * FROM planning_calendar_events WHERE workspace_id=? AND id=?').get(ws,id);changed(ws,user,'calendar_event',id,'create',c.get('userEmail'));return c.json(eventDto(row),201) })
planningRoutes.patch('/:id/planning/calendar-events/:eventId', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c);if(!b||(!Number.isInteger(b.expectedVersion)&&!Number.isFinite(b.expectedUpdatedAt)))return c.json({error:'需提供 expectedVersion'},400);if('assigneeId'in b&&!validAssignee(ws,b.assigneeId))return c.json({error:'负责人不是工作区成员'},400);const old=db.prepare('SELECT * FROM planning_calendar_events WHERE workspace_id=? AND id=? AND deleted_at IS NULL').get(ws,c.req.param('eventId'));if(!old)return c.json({error:'日程不存在'},404);if((Number.isInteger(b.expectedVersion)&&old.version!==b.expectedVersion)||(Number.isFinite(b.expectedUpdatedAt)&&old.updated_at!==b.expectedUpdatedAt))return c.json({error:'日程已被其他成员修改，请重新加载后再试',code:'PLANNING_VERSION_CONFLICT',current:eventDto(old)},409);if(typeof b.title==='string'&&(!b.title.trim()||b.title.length>500))return c.json({error:'标题不能为空且最长 500 字'},400);const now=Date.now();replaceTags(ws,'calendar_event',old.id,b.tagIds,c.get('userId'),now);db.prepare(`UPDATE planning_calendar_events SET title=?,notes=?,start_at=?,end_at=?,all_day=?,group_id=?,todo_id=?,assignee_id=?,updated_by=?,updated_at=?,version=version+1 WHERE workspace_id=? AND id=?`).run(typeof b.title==='string'?b.title.trim():old.title,typeof b.notes==='string'?b.notes:old.notes,Number.isFinite(b.startAt)?b.startAt:old.start_at,'endAt'in b?(Number.isFinite(b.endAt)?b.endAt:null):old.end_at,'allDay'in b?(b.allDay?1:0):old.all_day,'groupId'in b?(b.groupId||null):old.group_id,'todoId'in b?(b.todoId||null):old.todo_id,'assigneeId'in b?(b.assigneeId||null):old.assignee_id,c.get('userId'),now,ws,old.id);const row=db.prepare('SELECT * FROM planning_calendar_events WHERE workspace_id=? AND id=?').get(ws,old.id);changed(ws,c.get('userId'),'calendar_event',old.id,'update',c.get('userEmail'));return c.json(eventDto(row)) })
planningRoutes.delete('/:id/planning/calendar-events/:eventId', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const now=Date.now(),x=db.prepare('UPDATE planning_calendar_events SET deleted_at=?,updated_at=?,updated_by=?,version=version+1 WHERE workspace_id=? AND id=? AND deleted_at IS NULL').run(now,now,c.get('userId'),ws,c.req.param('eventId'));if(!x.changes)return c.json({error:'日程不存在'},404);changed(ws,c.get('userId'),'calendar_event',c.req.param('eventId'),'delete',c.get('userEmail'));return c.json({success:true}) })
planningRoutes.get('/:id/planning/reminder-deliveries/active', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);return c.json(listActiveDeliveries(db,ws,c.get('userId'))) })
planningRoutes.post('/:id/planning/reminder-deliveries/:deliveryId/acknowledge', c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const now=Date.now(),x=db.prepare("UPDATE planning_reminder_deliveries SET status='acknowledged',acknowledged_at=?,updated_at=? WHERE workspace_id=? AND id=? AND recipient_id=? AND status='pending'").run(now,now,ws,c.req.param('deliveryId'),c.get('userId'));return x.changes?c.json({success:true}):c.json({error:'提醒不存在或已处理'},404) })
planningRoutes.post('/:id/planning/reminder-deliveries/:deliveryId/snooze', async c => { const mw=authMiddleware(c);if(mw)return mw;const ws=access(c);if(!ws)return c.json({error:'无权访问工作区'},403);const b=await body(c),minutes=b?.minutes;if(!Number.isInteger(minutes)||minutes<1||minutes>10080)return c.json({error:'minutes 必须为 1 到 10080'},400);const now=Date.now(),x=db.prepare('UPDATE planning_reminder_deliveries SET snoozed_until=?,last_notified_at=NULL,updated_at=? WHERE workspace_id=? AND id=? AND recipient_id=? AND status=\'pending\'').run(now+minutes*60000,now,ws,c.req.param('deliveryId'),c.get('userId'));return x.changes?c.json({success:true}):c.json({error:'提醒不存在或已处理'},404) })
