import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const appRoot = path.resolve(scriptDir, '..')
const sourceDir = path.join(appRoot, 'node_modules', '@silurus', 'ooxml', 'dist')
const publicDir = path.join(appRoot, 'src', 'renderer', 'public', 'vendor', 'ooxml')

if (!fs.existsSync(sourceDir)) {
  throw new Error(`@silurus/ooxml dist directory does not exist: ${sourceDir}`)
}

fs.rmSync(publicDir, { recursive: true, force: true })
fs.mkdirSync(publicDir, { recursive: true })

for (const entry of fs.readdirSync(sourceDir, { withFileTypes: true })) {
  const source = path.join(sourceDir, entry.name)
  const target = path.join(publicDir, entry.name)
  fs.cpSync(source, target, { recursive: true })
}

const manifest = {}
for (const format of ['docx', 'xlsx', 'pptx']) {
  const source = path.join(sourceDir, `${format}_parser_bg.wasm`)
  const bytes = fs.readFileSync(source)
  const hash = crypto.createHash('sha256').update(bytes).digest('hex').slice(0, 16)
  const hashedName = `${format}_parser_bg.${hash}.wasm`
  fs.copyFileSync(source, path.join(publicDir, hashedName))
  manifest[format] = hashedName
}

fs.writeFileSync(
  path.join(publicDir, 'wasm-manifest.mjs'),
  `// Generated by scripts/build-ooxml.mjs. Do not edit.\nexport default ${JSON.stringify(manifest, null, 2)};\n`,
)

const copiedFiles = fs.readdirSync(publicDir).length
console.log(`[ooxml] copied ${copiedFiles} files to src/renderer/public/vendor/ooxml`)
console.log(`[ooxml] wasm manifest: ${JSON.stringify(manifest)}`)
